"""Add user_preferences table

Revision ID: 842c96b95eed
Revises: 0004_catalog_local
Create Date: 2026-06-14 14:51:13.564410
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '842c96b95eed'
down_revision: Union[str, None] = '0004_catalog_local'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.drop_constraint(op.f('deliveries_order_id_key'), 'deliveries', type_='unique')
    op.drop_index(op.f('ix_deliveries_order_id'), table_name='deliveries')
    op.create_index(op.f('ix_deliveries_order_id'), 'deliveries', ['order_id'], unique=True)
    op.drop_constraint(op.f('missions_slug_key'), 'missions', type_='unique')
    op.drop_index(op.f('ix_missions_slug'), table_name='missions')
    op.create_index(op.f('ix_missions_slug'), 'missions', ['slug'], unique=True)
    op.drop_constraint(op.f('payments_order_id_key'), 'payments', type_='unique')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=True)
    op.drop_index(op.f('ix_qcommerce_products_embedding_hnsw'), table_name='qcommerce_products', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_index(op.f('ix_qcommerce_products_category'), 'qcommerce_products', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qcommerce_products_category'), table_name='qcommerce_products')
    op.create_index(op.f('ix_qcommerce_products_embedding_hnsw'), 'qcommerce_products', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_unique_constraint(op.f('payments_order_id_key'), 'payments', ['order_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_missions_slug'), table_name='missions')
    op.create_index(op.f('ix_missions_slug'), 'missions', ['slug'], unique=False)
    op.create_unique_constraint(op.f('missions_slug_key'), 'missions', ['slug'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_deliveries_order_id'), table_name='deliveries')
    op.create_index(op.f('ix_deliveries_order_id'), 'deliveries', ['order_id'], unique=False)
    op.create_unique_constraint(op.f('deliveries_order_id_key'), 'deliveries', ['order_id'], postgresql_nulls_not_distinct=False)
    op.drop_table('user_preferences')
    # ### end Alembic commands ###
